### ISSUE TITLE
full examples?

### ISSUE THREAD

**Issue by heshpdx** [kno10/python-kmedoids#5]
Hi, do you have a full example available with a sample data set and expected output?

I followed the directions in the README.md and got to this issue:
`AttributeError: module 'kmedoids' has no attribute 'fasterpam'`

I used `help("kmedoids")` to determine that the function is not fasterpam, but rather fasterpam_{i32, i64, f32, f64}.  Am I missing a step to get the API cited in the docs?

I am running Ubuntu 20 on a newer aarch64 machine, with rustc 1.57.0 and Python 3.8.10.

```
    _fasterpam_f64 = fasterpam_f64(...)
        Run $variant k-medoids clustering function for $type precision
        
        :param dist: distance matrix
        :type dist: ndarray
        :param meds: initial medoids
        :type meds: ndarray
        :param max_iter: maximum number of iterations
        :type max_iter: int
        :return: k-medoids clustering result
        :rtype: KMedoidsResult
```

Thanks!

**Comment by kno10** [comment]
You appear to have wrongly used
```
import kmedoids.kmedoids
```
rather than the correct
```
import kmedoids
```

The former is the raw rust module, not the easy-to-use python wrapper.

The example in the README works fine, e.g., on colab:
```
!pip install kmedoids
import kmedoids
help(kmedoids.fasterpam)
```

**Comment by kno10** [comment]
Please try the update instructions to compile and install:
```
pip install maturin
maturin develop --release
```
Maturin takes care of installing the Rust library into the correct location along with the wrapper.

**Comment by kno10** [comment]
If you use pip without a virtualenv, it will usually install `$HOME/.local/bin` (on Linux), which was not on my path either; but that is [pip standard behavior](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-to-the-user-site), and you need to check pip documentation for the location on your OS.
As mentioned, you seem to have the nested (naming is by maturin, I could not get it to use `kmedoids._kmedoids` instead) module on your path. Any chance that you are *inside* the `kmedoids` folder, not in the root of the working tree? Where is the `kmedoids/__init__.py` on your python search path - because it appears that your python search path contains the .so first.

The distance matrix could be random values, yes. It's just not very meaningful to cluster random values, not even for the sake of an example. I don't like adding dependencies just for examples, but you trivially get an example distance matrix via
```python
from sklearn.datasets import load_iris
from sklearn.metrics.pairwise import euclidean_distances
distmatrix = euclidean_distances(load_iris().data)
```
but I don't think this adds value to the example, but it distracts and may give the false impression that there is a sklearn dependency.

**Comment by kno10** [comment]
The documentation by now also contains an example using the well-known MNIST data set.
